<definitions
    
     targetNamespace="http://tempuri.org/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://tempuri.org/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <import namespace="http://tempuri.org/" location="http://localhost:1120/Loja.asmx?WSDL"/>
    <plnk:partnerLinkType name="LojaSoap_PL">
        <plnk:role name="LojaSoap_Role">
            <plnk:portType name="tns:LojaSoap"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
